name: Build and deploy WAR app to Azure Web App - repositorio-central-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} # Eliminar o corregir esta línea si no se establece la URL en un paso anterior

    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'repositorio-central-backend'
          slot-name: 'Production'
          package: java-app/*.war
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_301A631409C64D2BA059FEB33196F69C }}
